### PR TITLE
Fix folder node render when there isn't children

### LINKED ISSUE #87: Unable to create an empty folder on loading
You can see that nodes `lost+found`, `cdrom`, `dev`, `etc` should be folders but they are tags.
I think, I can fix this and create a pull request.

### PR DESCRIPTION
**Pull request by lovery**
Fixed #87 

Added new folding type for empty nodes, because there is nothing to collapse or expand.
Reset folding type on create or remove of a child on a node.

### CODE REVIEW

**Comment by lovery** [comment]
The change isn't ready, but I want to show what I've done and to discuss with you about what should happen with nodes which are loaded lazy.

I've notice some strange behavior and I'm not sure how it should be.
Normally if you have a collapsed node and you want to add you want to add a children the node should expand you can can see the the new element and type a value but it is not the same with lazy loading nodes. When you click to to add new node it expands, you start typing new element name and after it finish loading your changes disappear.

May be we should check that current children and not remove all of them - to keep newest.

File: src/tree.ts [hunk 1]
```diff
@@ -169,6 +169,11 @@ export class Tree {
     } else {
       this._children = [child];
     }
+
+    this._setFoldingType();
+    if (this.isNodeCollapsed()) {
```
Comment (rychkog) [inline src/tree.ts]: We should not autoexpand nodes with async children

File: src/tree.ts [hunk 2]
```diff
@@ -237,6 +242,14 @@ export class Tree {
   }
 
   /**
+   * Check whether this tree has children.
+   * @returns {boolean} A flag indicating whether or not this tree has children.
+   */
+  public isEmpty(): boolean {
```
Comment (rychkog) [inline src/tree.ts]: hasChildren()

File: src/tree.ts [hunk 3]
```diff
@@ -237,6 +242,14 @@ export class Tree {
...
+    return !(this.childrenShouldBeLoaded() || _.get(this._children, 'length', 0) > 0);
```
Comment (rychkog) [inline src/tree.ts]: !_.isEmpty(this._children) || this.childrenShouldBeLoaded()

**Comment by rychkog** [comment]
@lovery Agree with according to adding new children when node is loading - it should be handled, but I think we just need to forbid adding new children while async children are loading

**Comment by rychkog** [comment]
Also why do we need special marker for nodes without children?

**Comment by lovery** [comment]
I think that there should be a new marker for this kind of nodes, because other way you won't be able to distinct empty node from a node with children.
In my use case all my nodes are loaded async and I don't want to have expand or collapse functionality no empty nodes, this will deceive my users that when they click expand something will show up, as in the other nodes.
Also if I have limited space and there is no option to put extra space to distinct level enough and my users won't be sure that leafs or empty nodes below an empty node aren't it's children.

**Comment by rychkog** [comment]
@lovery Ok, I see. In the example you provided - is `Music` node clickable?

**Comment by lovery** [comment]
I don't understand your question. `Music` is a lazy loading node.

**Comment by rychkog** [comment]
> I don't understand your question. Music is a lazy loading node.

I know it's just in some version of you PR it wasn't working - cause node was grayed out and not clickable

File: src/tree.ts [hunk 4]
```diff
@@ -22,7 +22,7 @@ export class Tree {
    * @param {boolean} [isBranch] - An option that makes a branch from created tree. Branch can have children.
    */
   public constructor(node: TreeModel, parent: Tree = null, isBranch: boolean = false) {
-    this.buildTreeFromModel(node, parent, isBranch);
+    this.buildTreeFromModel(node, parent, isBranch || Boolean(node.children));
```
Comment (rychkog) [inline src/tree.ts]: @lovery Do you want to find out whether a node contains anything or not by this check?

**Comment by rychkog** [comment]
@lovery We need to complete this feature and TreeController feature and then I want to rebase those on top of https://github.com/valor-software/ng2-tree/pull/91 (brings angular4, angular-cli, fix for children requested multiple times and other improvements)

**Comment by rychkog** [comment]
Waiting for you :)

File: src/tree.ts (hunk 4 above)
Comment (lovery) [inline src/tree.ts]: I want to check if a node has `children` property. If it has `children`, it should be a branch.
It doesn't mater if it has children or no.

**Comment by lovery** [comment]
Ok, I will start with testing tomorrow. I will try to do it as fast as possible :)

File: src/tree.ts (hunk 4 above)
Comment (rychkog) [inline src/tree.ts]: In this case
```
node.children = "hello"
Boolean(node.children)
```

will also return `true`. Maybe it should be more restrictive - `Array.isArray(node.children)`?

**Comment by lovery** [comment]
@rychkog I think I'm ready with the tests.
I'm not sure about this `has right statuses while loading its children asynchronously`
The timeouts are strange, I don't like them but this is the only way to test `childrenAreBeingLoaded` and other statuses.
Take a look and let me know if something is not right.

I will proceed with the other PR - controllers.

**Comment by rychkog** [comment]
@lovery Great! I will have a look at this PR ASAP! :) Also if you have questions or want to discuss smth. you can contact me via an email (should be visible on my profile page) in case I am not responding here.

**Comment by lauthieb** [comment]
Can we have a release including this fix please ? Thanks a lot !
